default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: myuser
  password: mypassword
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
